spring:
  datasource:
    driver:
      class: com.mysql.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/test}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    username: ${SPRING_DATASOURCE_USERNAME:root}

app:
  config:
    parcel-validation:
      reject:
        lowest: 51
        highest: -1
        cost-value: 0
        rule-name: REJECT_WEIGHT
      heavy:
        lowest: 11
        highest: 50
        cost-value: 20
        rule-name: HEAVY_WEIGHT
      small:
        highest: 1499
        lowest: 1
        cost-value: 0.03
        rule-name: SMALL_VOLUME
      medium:
        highest: 2500
        lowest: 1500
        cost-value: 0.04
        rule-name: MEDIUM_VOLUME
      large:
        highest: 0
        lowest: 2500
        cost-value: 0.05
        rule-name: LARGE_VOLUME
server:
  port: 8088
  servlet:
    context-path: /parcelservice/

connector:
  voucher-service:
    url: https://mynt-exam.mocklab.io/

